// Each entry is replaceable. Models use glTF Y-up, with their feet on the ground.
export const worlds = [
 {id:'sakura_courtyard',name:'Sakura Courtyard',short:'Sakura',style:'Japanese garden',color:'#c68e9c',ground:'#8c9c66',edge:'#c7ba9b',texture:'grass',description:'Vermilion shrines, stone paths, and spring canopies.',prompt:'Create a Japanese garden with cherry blossoms, branching paths, and a guardian Boss.',player:'sakura_courtyard_player',boss:'sakura_courtyard_boss',miniature:'sakura'},
 {id:'neon_switchyard',name:'Neon Switchyard',short:'Cyberpunk',style:'Neon cyberpunk',color:'#8f86c5',ground:'#26394c',edge:'#626e86',texture:'asphalt',description:'Luminous storefronts and machines after dark.',prompt:'Create a neon cyberpunk district with futuristic vehicles, branching alleys, a courier, and an armored Boss.',player:'neon_switchyard_player',boss:'neon_switchyard_boss',miniature:'neon'},
 {id:'desert_caravanserai',name:'Dune Court',short:'Dune Court',style:'Desert caravanserai',color:'#c89956',ground:'#edd4a7',edge:'#c8a575',texture:'sand',description:'Sandstone courts, indigo awnings, and wind-shaped dunes.',prompt:'Create a desert caravanserai with sandstone arches, shaded markets, winding sand paths, a nomad, and an armored dune warden.',player:'desert_caravanserai_player',boss:'desert_caravanserai_boss',miniature:'desert'},
 {id:'snowbound_outpost',name:'Frostwatch Outpost',short:'Frostwatch',style:'Snowbound mountain outpost',color:'#85aabb',ground:'#f1f6f8',edge:'#adc4cf',texture:'snow',description:'Snow-laden timber lodges beside a frozen alpine stream.',prompt:'Create a snowy mountain outpost with timber lodges, a frozen-stream crossing, an observation terrace, a winter ranger, and a frost-armored sentinel.',player:'snowbound_outpost_player',boss:'snowbound_outpost_boss',miniature:'snow'},
 {id:'mediterranean_courtyard',name:'Sunward Sentinel',short:'Sunward',style:'Mediterranean courtyard',color:'#bda164',ground:'#a4ae79',edge:'#d5c7ab',texture:'stone',description:'Ivory arcades, cobalt shutters, olive groves and a bronze guardian.',prompt:'Create a sunlit Mediterranean courtyard with limestone arcades, blue doors, a fountain garden, connected olive paths, a traveler and a bronze sentinel.',player:'mediterranean_courtyard_player',boss:'mediterranean_courtyard_boss',miniature:'sunward'},
 {id:'underwater_habitat',name:'Abyssal Lock',short:'Abyssal',style:'Underwater research habitat',color:'#3c95a4',ground:'#809fa5',edge:'#66818a',texture:'sand',description:'Pressure doors, ocean-facing galleries, and a deep-sea guardian.',prompt:'Create an underwater research habitat with dry connected rooms, an observation gallery, marine laboratories, a diver player, and a pressure-suit guardian Boss.',player:'underwater_habitat_player',boss:'underwater_habitat_boss',miniature:'abyssal'},
 {id:'amber_cloister',name:'Amber Cloister',short:'Cloister',style:'Sunlit monastery',color:'#cba063',ground:'#aaa075',edge:'#c8b89b',texture:'stone',description:'Warm masonry, cloister arcades, and a horned sentinel.',prompt:'Create a sunlit monastery with cloister arches, garden paths, and a towering bull guardian.',player:'amber_cloister_player',boss:'amber_cloister_boss',miniature:'cloister',showcase:false},
 {id:'steampunk_foundry',name:'Ironwake Foundry',short:'Foundry',style:'Steampunk industrial works',color:'#aa7854',ground:'#676563',edge:'#957456',texture:'stone',description:'Riveted boilers, red brick and elevated industrial passages.',prompt:'Create a steampunk foundry with red-brick workshops, riveted boilers, branching industrial routes, an engineer player and a mechanical Boss.',showcase:false}
];
export const discWorlds = worlds.filter(world => world.showcase !== false);

